### ISSUE TITLE
Eval module

### ISSUE THREAD

**Issue by pw-pw** [thomyphan/rl4mapf#3]
Hello, I encountered a mismatch in network dimensions while evaluating the model. I found that only when the number of trained agents is equal to the number of evaluated agents, will there be no errors. I would like to ask how to resolve this situation
![2024-06-03 11-14-47屏幕截图](https://github.com/thomyphan/rl4mapf/assets/141016135/c67e4326-21f9-418e-a757-3d3a4ee806ac)

**Comment by thomyphan** [comment]
The policy networks will work with an arbitrary number of agents, but the critic/mixing network may have issues because it relies on a fixed dimension. Therefore, I suggest an evaluation flag in the method **A2CController.load_model_weights**, where the critic model is not loaded (lines 50-55 in **cactus/controller/a2c_controller.py**).

If you just want to run the evaluation code, you can just comment these lines out.

**Comment by pw-pw** [comment]
Okay, I have modified the code according to your suggestions and it can now work. Thank you very much
